#!/usr/bin/env bash
# Regenera la migración 0001 desde los modelos, mientras el esquema todavía no
# está desplegado en ningún entorno. Una vez que haya una base en producción,
# los cambios van en migraciones nuevas y este script deja de usarse.
set -euo pipefail
cd "$(dirname "$0")/.."

VERSIONES=src/backend_normativo/migrations/versions
TMP=$(mktemp -d)
trap 'rm -rf "$TMP"' EXIT

# 0002 depende de 0001: se aparta para que el autogenerado no vea una cadena rota.
mv "$VERSIONES"/0002_*.py "$TMP"/ 2>/dev/null || true
rm -f "$VERSIONES"/0001_*.py

export PGPASSWORD=${PGPASSWORD:-postgres}
psql -h 127.0.0.1 -U postgres -c "DROP DATABASE IF EXISTS backend_normativo WITH (FORCE);" \
                               -c "CREATE DATABASE backend_normativo;" >/dev/null

.venv/bin/alembic revision --autogenerate -m "esquema inicial" >/dev/null

python3 - "$VERSIONES" <<'PY'
import pathlib, re, sys
versiones = pathlib.Path(sys.argv[1])
src = next(p for p in versiones.glob("*.py") if not p.name.startswith("00"))
dst = versiones / "0001_esquema_inicial.py"
s = src.read_text()
rev = re.search(r"revision: str = '([^']+)'", s).group(1)
s = re.sub(
    r'"""esquema inicial\n\nRevision ID: [^\n]*\nRevises: *\nCreate Date: [^\n]*\n"""',
    '"""Esquema inicial del corpus normativo: las 53 tablas del diccionario.\n\n'
    "Crea tablas, claves, vocabularios controlados (`CHECK`), la restricción de\n"
    "exclusión temporal de los valores de parámetros e índices. Las reglas que\n"
    "PostgreSQL solo expresa con triggers, funciones, vistas o roles se aplican\n"
    'en la migración 0002.\n\nRevision ID: 0001_esquema_inicial\nRevises:\n"""',
    s,
)
s = s.replace(f"revision: str = '{rev}'", 'revision: str = "0001_esquema_inicial"')
s = s.replace(
    "def upgrade() -> None:\n    # ### commands auto generated by Alembic - please adjust! ###\n",
    "def upgrade() -> None:\n"
    "    # `gen_random_uuid()` para las PK internas y `btree_gist` para la\n"
    "    # exclusión temporal, que combina igualdad y solapamiento de rangos.\n"
    '    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")\n'
    '    op.execute("CREATE EXTENSION IF NOT EXISTS btree_gist")\n\n',
)
s = s.replace(
    "def downgrade() -> None:\n    # ### commands auto generated by Alembic - please adjust! ###\n",
    "def downgrade() -> None:\n",
)
s = s.replace("    # ### end Alembic commands ###\n", "")
dst.write_text(s)
src.unlink()
PY

mv "$TMP"/0002_*.py "$VERSIONES"/ 2>/dev/null || true
.venv/bin/ruff format "$VERSIONES" >/dev/null
.venv/bin/alembic upgrade head
.venv/bin/alembic check
